FROM node:20.12.0-alpine3.19

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json pnpm-lock.yaml pnpm-workspace.yaml ./

COPY apps ./apps
COPY packages ./packages

RUN pnpm install --filter ./apps --filter ./packages
RUN pnpm run db:generate
RUN pnpm run build

CMD [ "pnpm","run","start-user-app" ]