-- NimbleWallet core schema (Postgres schema: wallet).
-- Money is stored as minor units (paise) in BIGINT. Razorpay is the sole
-- funding rail, so there is no bank/provider concept — only an optional
-- payment_method captured from Razorpay for display.

create table app_user (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null unique,
    password_hash varchar(255),
    phone_number  varchar(20) unique,
    name          varchar(255) not null,
    google_id     varchar(255),
    auth_provider varchar(20)
);

create table wallet_balance (
    id           bigint generated by default as identity primary key,
    user_id      bigint not null unique references app_user (id),
    amount_minor bigint not null default 0,
    locked_minor bigint not null default 0
);

create table deposit_order (
    id             bigint generated by default as identity primary key,
    user_id        bigint      not null references app_user (id),
    order_token    varchar(255) not null unique,
    amount_minor   bigint      not null,
    status         varchar(20) not null,          -- PENDING | COMPLETED | FAILED
    payment_method varchar(20),                   -- UPI | CARD | NETBANKING | WALLET
    created_at     timestamptz not null default now()
);

create table peer_transfer (
    id           bigint generated by default as identity primary key,
    from_user_id bigint      not null references app_user (id),
    to_user_id   bigint      not null references app_user (id),
    amount_minor bigint      not null,
    created_at   timestamptz not null default now()
);

create index idx_deposit_order_user on deposit_order (user_id);
create index idx_peer_transfer_from on peer_transfer (from_user_id);
create index idx_peer_transfer_to on peer_transfer (to_user_id);
