import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "../../provider";
import { AppbarClient } from "../components/AppbarClient";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <Providers>
        <body>
          <div className="min-w-screen min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
            <AppbarClient />
            {children}
          </div>
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
